/* Story location data. */

const CHNPP_STORY = {
  titleKey:"storyLocations.chnpp.title",
  descriptionKey:"storyLocations.chnpp.description",
  questKey:"storyLocations.chnpp.quest",
  objectiveKey:"storyLocations.chnpp.objective",
  rewardKey:"storyLocations.chnpp.reward",
  rewardData:{
    xp:900,
    money:1000,
    items:[{id:"ammo",qty:40},{id:"medkit",qty:2},{id:"legendary_hide",qty:3}],
    equipmentRarity:"legendary"
  },
  required:[
    "chnpp_checkpoint_register","chnpp_inner_perimeter_key",
    "chnpp_project_1037_order","chnpp_personnel_list","chnpp_service_plan",
    "chnpp_transport_access_code","chnpp_transport_gate_fuse","chnpp_transport_gate_open",
    "chnpp_last_shift_log","chnpp_chief_electrician_key","chnpp_repair_component",
    "chnpp_power_fuse_a","chnpp_power_fuse_b","chnpp_power_scheme","chnpp_power_restored",
    "chnpp_operator_log","chnpp_lower_level_code","chnpp_signal_tape",
    "chnpp_isolation_protocol_4","chnpp_elevator_level12_scheme",
    "chnpp_access_card_1037","chnpp_airlock_fuse","chnpp_emergency_open_key","chnpp_airlock_open",
    "chnpp_transmitter_access_key","chnpp_final_protocol_1037","chnpp_object_personnel_list",
    "chnpp_power_module_1037","chnpp_transmitter_powered",
    "chnpp_operator_authorization_key","chnpp_signal_archive_1037",
    "chnpp_final_boss","chnpp_core_module_1037"
  ],
  quests:[
    {
      requirements:["chnpp_checkpoint_register","chnpp_inner_perimeter_key"],
      consumeItems:["chnpp_checkpoint_register","chnpp_inner_perimeter_key"],
      labelKey:"storyLocations.chnpp.quests.q1",
      rewardData:{xp:110,money:60,material:"epic_hide",qty:1}
    },
    {
      requirements:["chnpp_project_1037_order","chnpp_personnel_list","chnpp_service_plan"],
      consumeItems:["chnpp_project_1037_order","chnpp_personnel_list","chnpp_service_plan"],
      labelKey:"storyLocations.chnpp.quests.q2",
      rewardData:{xp:120,money:65,material:"epic_hide",qty:1}
    },
    {
      requirements:["chnpp_transport_access_code","chnpp_transport_gate_fuse","chnpp_transport_gate_open"],
      consumeItems:["chnpp_transport_access_code","chnpp_transport_gate_fuse"],
      labelKey:"storyLocations.chnpp.quests.q3",
      rewardData:{xp:125,money:70,material:"epic_hide",qty:1}
    },
    {
      requirements:["chnpp_last_shift_log","chnpp_chief_electrician_key","chnpp_repair_component"],
      consumeItems:["chnpp_last_shift_log","chnpp_chief_electrician_key","chnpp_repair_component"],
      labelKey:"storyLocations.chnpp.quests.q4",
      rewardData:{xp:135,money:75,material:"epic_hide",qty:1}
    },
    {
      requirements:["chnpp_power_fuse_a","chnpp_power_fuse_b","chnpp_power_scheme","chnpp_power_restored"],
      consumeItems:["chnpp_power_fuse_a","chnpp_power_fuse_b","chnpp_power_scheme"],
      labelKey:"storyLocations.chnpp.quests.q5",
      rewardData:{xp:140,money:80,material:"epic_hide",qty:1}
    },
    {
      requirements:["chnpp_operator_log","chnpp_lower_level_code","chnpp_signal_tape"],
      consumeItems:["chnpp_operator_log","chnpp_lower_level_code","chnpp_signal_tape"],
      labelKey:"storyLocations.chnpp.quests.q6",
      rewardData:{xp:150,money:90,material:"epic_hide",qty:2}
    },
    {
      requirements:["chnpp_isolation_protocol_4","chnpp_elevator_level12_scheme"],
      consumeItems:["chnpp_isolation_protocol_4","chnpp_elevator_level12_scheme"],
      labelKey:"storyLocations.chnpp.quests.q7",
      rewardData:{xp:160,money:100,material:"epic_hide",qty:2}
    },
    {
      requirements:["chnpp_access_card_1037","chnpp_airlock_fuse","chnpp_emergency_open_key","chnpp_airlock_open"],
      consumeItems:["chnpp_access_card_1037","chnpp_airlock_fuse","chnpp_emergency_open_key"],
      labelKey:"storyLocations.chnpp.quests.q8",
      rewardData:{xp:170,money:110,material:"epic_hide",qty:2}
    },
    {
      requirements:["chnpp_transmitter_access_key","chnpp_final_protocol_1037","chnpp_object_personnel_list"],
      consumeItems:["chnpp_transmitter_access_key","chnpp_final_protocol_1037","chnpp_object_personnel_list"],
      labelKey:"storyLocations.chnpp.quests.q9",
      rewardData:{xp:185,money:125,material:"legendary_hide",qty:1}
    },
    {
      requirements:["chnpp_power_module_1037","chnpp_transmitter_powered","chnpp_operator_authorization_key","chnpp_signal_archive_1037","chnpp_final_boss","chnpp_core_module_1037"],
      consumeItems:["chnpp_power_module_1037","chnpp_operator_authorization_key","chnpp_signal_archive_1037","chnpp_core_module_1037"],
      labelKey:"storyLocations.chnpp.quests.q10",
      rewardData:{xp:250,money:200,material:"legendary_hide",qty:2}
    }
  ],
  scenes:{
    main:{
      image:"chnpp.webp",
      introKey:"storyIntro.chnpp.main",
      titleKey:"storyLocations.chnpp.scenes.main.title",
      hintKey:"storyLocations.chnpp.scenes.main.hint",
      areas:[
        // Keep the ten map points compact and non-overlapping. This prevents a
        // later locked point from intercepting a click intended for the current one.
        {target:"checkpoint_exterior",box:[27,82,18,13],marker:[36,88],labelKey:"storyLocations.chnpp.scenes.main.checkpoint"},
        {target:"admin_exterior",box:[19,64,23,14],marker:[30,71],labelKey:"storyLocations.chnpp.scenes.main.admin",requires:["chnpp_inner_perimeter_key"],failKey:"storyLocations.chnpp.scenes.main.adminLocked"},
        {target:"transport_exterior",box:[50,47,20,15],marker:[60,54],labelKey:"storyLocations.chnpp.scenes.main.transport",requires:["chnpp_service_plan"],failKey:"storyLocations.chnpp.scenes.main.transportLocked"},
        {target:"machine_exterior",box:[9,39,27,15],marker:[22,46],labelKey:"storyLocations.chnpp.scenes.main.machine",requires:["chnpp_transport_gate_open"],failKey:"storyLocations.chnpp.scenes.main.machineLocked"},
        {target:"electrical_exterior",box:[5,24,26,13],marker:[18,30],labelKey:"storyLocations.chnpp.scenes.main.electrical",requires:["chnpp_chief_electrician_key"],failKey:"storyLocations.chnpp.scenes.main.electricalLocked"},
        {target:"control_corridor",box:[72,35,24,15],marker:[84,42],labelKey:"storyLocations.chnpp.scenes.main.control",requires:["chnpp_power_restored"],failKey:"storyLocations.chnpp.scenes.main.controlLocked"},
        {target:"sarcophagus_exterior",box:[56,14,22,14],marker:[67,21],labelKey:"storyLocations.chnpp.scenes.main.sarcophagus",requires:["chnpp_signal_tape"],failKey:"storyLocations.chnpp.scenes.main.sarcophagusLocked"},
        {target:"underreactor_corridor",box:[44,30,18,12],marker:[53,36],labelKey:"storyLocations.chnpp.scenes.main.underreactor",requires:["chnpp_elevator_level12_scheme"],failKey:"storyLocations.chnpp.scenes.main.underreactorLocked"},
        {target:"object_entrance",box:[70,59,24,15],marker:[82,66],labelKey:"storyLocations.chnpp.scenes.main.object1037",requires:["chnpp_airlock_open"],failKey:"storyLocations.chnpp.scenes.main.objectLocked"},
        {target:"signal_power",box:[82,15,15,13],marker:[89,21],labelKey:"storyLocations.chnpp.scenes.main.signalSource",requires:["chnpp_final_protocol_1037"],failKey:"storyLocations.chnpp.scenes.main.signalLocked"}
      ]
    },

    checkpoint_exterior:{
      image:"chnpp_checkpoint_exterior.webp",
      introKey:"storyIntro.chnpp.checkpoint",
      titleKey:"storyLocations.chnpp.scenes.checkpointExterior.title",
      hintKey:"storyLocations.chnpp.scenes.checkpointExterior.hint",
      parent:"main",
      areas:[
        {target:"checkpoint_interior",box:[69,32,17,24],marker:[77,43],labelKey:"storyLocations.chnpp.scenes.checkpointExterior.enter"},
        {id:"chnpp_checkpoint_medkit",box:[1,68,27,13],checkAt:[14,74],loot:[{id:"medkit",qty:1}],messageKey:"storyLocations.chnpp.scenes.checkpointExterior.medkitMessage"},
        {id:"chnpp_checkpoint_ammo",box:[25,77,18,10],checkAt:[33,82],loot:[{id:"ammo",qty:12}],messageKey:"storyLocations.chnpp.scenes.checkpointExterior.ammoMessage"}
      ]
    },
    checkpoint_interior:{
      image:"chnpp_checkpoint_interior.webp",
      titleKey:"storyLocations.chnpp.scenes.checkpointInterior.title",
      hintKey:"storyLocations.chnpp.scenes.checkpointInterior.hint",
      parent:"checkpoint_exterior",
      areas:[
        {id:"chnpp_checkpoint_register",box:[30,56,35,15],checkAt:[48,63],loot:[{id:"chnpp_checkpoint_register",qty:1}],messageKey:"storyLocations.chnpp.scenes.checkpointInterior.registerMessage"},
        {id:"chnpp_inner_perimeter_key",box:[57,66,13,8],checkAt:[64,70],loot:[{id:"chnpp_inner_perimeter_key",qty:1}],messageKey:"storyLocations.chnpp.scenes.checkpointInterior.keyMessage"},
        {id:"chnpp_checkpoint_scrap",box:[78,66,19,11],checkAt:[87,71],loot:[{id:"scrap",qty:2}],messageKey:"storyLocations.chnpp.scenes.checkpointInterior.scrapMessage"}
      ]
    },

    admin_exterior:{
      image:"chnpp_administrative_building_exterior.webp",
      introKey:"storyIntro.chnpp.admin",
      titleKey:"storyLocations.chnpp.scenes.adminExterior.title",
      hintKey:"storyLocations.chnpp.scenes.adminExterior.hint",
      parent:"main",
      areas:[
        {target:"admin_office",box:[31,42,23,28],marker:[42,56],labelKey:"storyLocations.chnpp.scenes.adminExterior.enter"}
      ]
    },
    admin_office:{
      image:"chnpp_administrative_office_interior.webp",
      titleKey:"storyLocations.chnpp.scenes.adminOffice.title",
      hintKey:"storyLocations.chnpp.scenes.adminOffice.hint",
      parent:"admin_exterior",
      areas:[
        {id:"chnpp_project_1037_order",box:[47,61,30,22],checkAt:[62,72],loot:[{id:"chnpp_project_1037_order",qty:1}],messageKey:"storyLocations.chnpp.scenes.adminOffice.orderMessage"},
        {id:"chnpp_personnel_list",box:[77,62,22,22],checkAt:[88,72],loot:[{id:"chnpp_personnel_list",qty:1}],messageKey:"storyLocations.chnpp.scenes.adminOffice.personnelMessage"},
        {id:"chnpp_service_plan",box:[3,61,43,24],checkAt:[25,72],loot:[{id:"chnpp_service_plan",qty:1}],messageKey:"storyLocations.chnpp.scenes.adminOffice.planMessage"},
        {target:"admin_safe",box:[51,30,23,24],marker:[62,42],labelKey:"storyLocations.chnpp.scenes.adminOffice.safe"}
      ]
    },
    admin_safe:{
      image:"chnpp_administrative_safe_loot.webp",
      titleKey:"storyLocations.chnpp.scenes.adminSafe.title",
      hintKey:"storyLocations.chnpp.scenes.adminSafe.hint",
      parent:"admin_office",
      areas:[
        {id:"chnpp_safe_dosimeter",box:[31,30,14,15],checkAt:[38,37],loot:[{id:"basic_dosimeter",qty:1,rarity:"legendary"}],messageKey:"storyLocations.chnpp.scenes.adminSafe.dosimeterMessage"},
        {id:"chnpp_safe_medkit",box:[38,71,18,10],checkAt:[47,76],loot:[{id:"medkit",qty:1}],messageKey:"storyLocations.chnpp.scenes.adminSafe.medkitMessage"},
        {id:"chnpp_safe_ammo",box:[42,49,18,12],checkAt:[51,55],loot:[{id:"ammo",qty:15}],messageKey:"storyLocations.chnpp.scenes.adminSafe.ammoMessage"}
      ]
    },

    transport_exterior:{
      image:"chnpp_transport_corridor_exterior.webp",
      introKey:"storyIntro.chnpp.transport",
      titleKey:"storyLocations.chnpp.scenes.transportExterior.title",
      hintKey:"storyLocations.chnpp.scenes.transportExterior.hint",
      parent:"main",
      areas:[
        {target:"transport_control",box:[16,44,13,16],marker:[22,52],labelKey:"storyLocations.chnpp.scenes.transportExterior.controlRoom"},
        {id:"chnpp_transport_scrap",box:[77,44,22,23],checkAt:[88,55],loot:[{id:"scrap",qty:3}],messageKey:"storyLocations.chnpp.scenes.transportExterior.scrapMessage"},
        {id:"chnpp_transport_tools",box:[15,50,17,12],checkAt:[23,56],loot:[{id:"toolkit",qty:1}],messageKey:"storyLocations.chnpp.scenes.transportExterior.toolsMessage"}
      ]
    },
    transport_control:{
      image:"chnpp_transport_corridor_control_room.webp",
      titleKey:"storyLocations.chnpp.scenes.transportControl.title",
      hintKey:"storyLocations.chnpp.scenes.transportControl.hint",
      parent:"transport_exterior",
      areas:[
        {id:"chnpp_transport_access_code",box:[33,53,27,13],checkAt:[46,59],loot:[{id:"chnpp_transport_access_code",qty:1}],messageKey:"storyLocations.chnpp.scenes.transportControl.codeMessage"},
        {id:"chnpp_transport_gate_fuse",box:[53,55,20,13],checkAt:[63,61],loot:[{id:"chnpp_transport_gate_fuse",qty:1}],messageKey:"storyLocations.chnpp.scenes.transportControl.fuseMessage"},
        {id:"chnpp_transport_gate_open",action:true,box:[69,34,16,20],checkAt:[77,44],requires:["chnpp_transport_access_code","chnpp_transport_gate_fuse"],failKey:"storyLocations.chnpp.scenes.transportControl.gateLocked",messageKey:"storyLocations.chnpp.scenes.transportControl.gateMessage"}
      ]
    },

    machine_exterior:{
      image:"chnpp_machine_hall_exterior.webp",
      introKey:"storyIntro.chnpp.machine",
      titleKey:"storyLocations.chnpp.scenes.machineExterior.title",
      hintKey:"storyLocations.chnpp.scenes.machineExterior.hint",
      parent:"main",
      areas:[
        {target:"machine_hall",box:[51,35,29,24],marker:[65,47],labelKey:"storyLocations.chnpp.scenes.machineExterior.enter"},
        {id:"chnpp_machine_water",box:[12,61,24,12],checkAt:[24,67],loot:[{id:"water",qty:2}],messageKey:"storyLocations.chnpp.scenes.machineExterior.waterMessage"},
        {id:"chnpp_machine_medkit",box:[0,74,25,16],checkAt:[12,82],loot:[{id:"medkit",qty:1}],messageKey:"storyLocations.chnpp.scenes.machineExterior.medkitMessage"},
        {id:"chnpp_machine_scrap",box:[73,64,26,20],checkAt:[86,73],loot:[{id:"scrap",qty:3}],messageKey:"storyLocations.chnpp.scenes.machineExterior.scrapMessage"}
      ]
    },
    machine_hall:{
      image:"chnpp_machine_hall_interior.webp",
      titleKey:"storyLocations.chnpp.scenes.machineHall.title",
      hintKey:"storyLocations.chnpp.scenes.machineHall.hint",
      parent:"machine_exterior",
      areas:[
        {target:"machine_lower",box:[36,51,29,17],marker:[51,59],labelKey:"storyLocations.chnpp.scenes.machineHall.lower"},
        {id:"chnpp_machine_hall_water",box:[13,61,28,16],checkAt:[27,69],loot:[{id:"water",qty:2}],messageKey:"storyLocations.chnpp.scenes.machineHall.waterMessage"},
        {id:"chnpp_machine_hall_toolkit",box:[27,72,23,15],checkAt:[39,79],loot:[{id:"toolkit",qty:1}],messageKey:"storyLocations.chnpp.scenes.machineHall.toolkitMessage"},
        {id:"chnpp_repair_component",box:[50,78,16,11],checkAt:[58,83],loot:[{id:"chnpp_repair_component",qty:1}],messageKey:"storyLocations.chnpp.scenes.machineHall.componentMessage"},
        {id:"chnpp_machine_hall_medkit",box:[62,82,21,14],checkAt:[72,89],loot:[{id:"medkit",qty:1}],messageKey:"storyLocations.chnpp.scenes.machineHall.medkitMessage"}
      ]
    },
    machine_lower:{
      image:"chnpp_machine_hall_lower_technical_level.webp",
      titleKey:"storyLocations.chnpp.scenes.machineLower.title",
      hintKey:"storyLocations.chnpp.scenes.machineLower.hint",
      parent:"machine_hall",
      areas:[
        {id:"chnpp_machine_lower_medkit",box:[82,45,17,12],checkAt:[91,51],loot:[{id:"medkit",qty:1}],messageKey:"storyLocations.chnpp.scenes.machineLower.medkitMessage"},
        {id:"chnpp_machine_lower_materials",box:[25,43,17,14],checkAt:[33,50],loot:[{id:"scrap",qty:2}],messageKey:"storyLocations.chnpp.scenes.machineLower.materialMessage"},
        {id:"chnpp_machine_lower_water",box:[87,54,12,10],checkAt:[93,59],loot:[{id:"water",qty:1}],messageKey:"storyLocations.chnpp.scenes.machineLower.waterMessage"},
        {id:"chnpp_last_shift_log",box:[7,61,45,22],checkAt:[30,72],loot:[{id:"chnpp_last_shift_log",qty:1}],messageKey:"storyLocations.chnpp.scenes.machineLower.logMessage"},
        {id:"chnpp_chief_electrician_key",box:[42,78,22,12],checkAt:[53,84],loot:[{id:"chnpp_chief_electrician_key",qty:1}],messageKey:"storyLocations.chnpp.scenes.machineLower.keyMessage"}
      ]
    },

    electrical_exterior:{
      image:"chnpp_electrotechnical_block_exterior.webp",
      introKey:"storyIntro.chnpp.electrical",
      titleKey:"storyLocations.chnpp.scenes.electricalExterior.title",
      hintKey:"storyLocations.chnpp.scenes.electricalExterior.hint",
      parent:"main",
      areas:[
        {target:"electrical_switchgear",box:[34,37,32,31],marker:[50,52],labelKey:"storyLocations.chnpp.scenes.electricalExterior.enter"},
        {id:"chnpp_electrical_water",box:[55,73,22,12],checkAt:[66,79],loot:[{id:"water",qty:1}],messageKey:"storyLocations.chnpp.scenes.electricalExterior.waterMessage"},
        {id:"chnpp_electrical_medkit",box:[80,82,19,11],checkAt:[90,87],loot:[{id:"medkit",qty:1}],messageKey:"storyLocations.chnpp.scenes.electricalExterior.medkitMessage"},
        {id:"chnpp_electrical_toolkit",box:[0,82,17,12],checkAt:[8,88],loot:[{id:"toolkit",qty:1}],messageKey:"storyLocations.chnpp.scenes.electricalExterior.toolkitMessage"}
      ]
    },
    electrical_switchgear:{
      image:"chnpp_electrotechnical_block_switchgear_room.webp",
      titleKey:"storyLocations.chnpp.scenes.electricalSwitchgear.title",
      hintKey:"storyLocations.chnpp.scenes.electricalSwitchgear.hint",
      parent:"electrical_exterior",
      areas:[
        {id:"chnpp_power_fuse_a",box:[2,73,11,10],checkAt:[7,78],loot:[{id:"chnpp_power_fuse_a",qty:1}],messageKey:"storyLocations.chnpp.scenes.electricalSwitchgear.fuseAMessage"},
        {id:"chnpp_power_fuse_b",box:[11,73,12,10],checkAt:[17,78],loot:[{id:"chnpp_power_fuse_b",qty:1}],messageKey:"storyLocations.chnpp.scenes.electricalSwitchgear.fuseBMessage"},
        {id:"chnpp_power_scheme",box:[1,56,57,20],checkAt:[29,65],loot:[{id:"chnpp_power_scheme",qty:1}],messageKey:"storyLocations.chnpp.scenes.electricalSwitchgear.schemeMessage"},
        {id:"chnpp_power_restored",action:true,box:[68,17,18,23],checkAt:[77,29],requires:["chnpp_power_fuse_a","chnpp_power_fuse_b","chnpp_power_scheme"],failKey:"storyLocations.chnpp.scenes.electricalSwitchgear.powerLocked",messageKey:"storyLocations.chnpp.scenes.electricalSwitchgear.powerMessage"}
      ]
    },

    control_corridor:{
      image:"chnpp_control_block_corridor_loot.webp",
      introKey:"storyIntro.chnpp.control",
      titleKey:"storyLocations.chnpp.scenes.controlCorridor.title",
      hintKey:"storyLocations.chnpp.scenes.controlCorridor.hint",
      parent:"main",
      areas:[
        {target:"control_main",box:[40,29,24,24],marker:[52,41],labelKey:"storyLocations.chnpp.scenes.controlCorridor.enter"},
        {id:"chnpp_control_water",box:[7,55,13,10],checkAt:[14,60],loot:[{id:"water",qty:1}],messageKey:"storyLocations.chnpp.scenes.controlCorridor.waterMessage"},
        {id:"chnpp_control_medkit",box:[82,54,15,11],checkAt:[89,59],loot:[{id:"medkit",qty:1}],messageKey:"storyLocations.chnpp.scenes.controlCorridor.medkitMessage"}
      ]
    },
    control_main:{
      image:"chnpp_control_block_main_room.webp",
      titleKey:"storyLocations.chnpp.scenes.controlMain.title",
      hintKey:"storyLocations.chnpp.scenes.controlMain.hint",
      parent:"control_corridor",
      areas:[
        {target:"communications_room",box:[84,29,10,17],marker:[89,37],labelKey:"storyLocations.chnpp.scenes.controlMain.communications"},
        {id:"chnpp_control_main_water",box:[29,65,12,16],checkAt:[35,73],loot:[{id:"water",qty:1}],messageKey:"storyLocations.chnpp.scenes.controlMain.waterMessage"},
        {id:"chnpp_control_main_food",box:[39,67,11,14],checkAt:[44,74],loot:[{id:"food",qty:1}],messageKey:"storyLocations.chnpp.scenes.controlMain.foodMessage"},
        {id:"chnpp_control_main_medkit",box:[48,71,20,14],checkAt:[58,78],loot:[{id:"medkit",qty:1}],messageKey:"storyLocations.chnpp.scenes.controlMain.medkitMessage"}
      ]
    },
    communications_room:{
      image:"chnpp_control_block_communications_room.webp",
      titleKey:"storyLocations.chnpp.scenes.communications.title",
      hintKey:"storyLocations.chnpp.scenes.communications.hint",
      parent:"control_main",
      areas:[
        {id:"chnpp_operator_log",box:[34,52,31,16],checkAt:[49,60],loot:[{id:"chnpp_operator_log",qty:1}],messageKey:"storyLocations.chnpp.scenes.controlMain.logMessage"},
        {id:"chnpp_signal_tape",box:[21,64,20,11],checkAt:[30,69],loot:[{id:"chnpp_signal_tape",qty:1}],messageKey:"storyLocations.chnpp.scenes.communications.tapeMessage"},
        {id:"chnpp_lower_level_code",box:[75,42,22,24],checkAt:[86,54],loot:[{id:"chnpp_lower_level_code",qty:1}],messageKey:"storyLocations.chnpp.scenes.communications.codeMessage"}
      ]
    },

    sarcophagus_exterior:{
      image:"chnpp_sarcophagus_exterior.webp",
      introKey:"storyIntro.chnpp.sarcophagus",
      titleKey:"storyLocations.chnpp.scenes.sarcophagusExterior.title",
      hintKey:"storyLocations.chnpp.scenes.sarcophagusExterior.hint",
      parent:"main",
      areas:[
        {target:"sarcophagus_service",box:[55,39,24,19],marker:[67,48],labelKey:"storyLocations.chnpp.scenes.sarcophagusExterior.enter"},
        {id:"chnpp_sarcophagus_water",box:[13,82,12,14],checkAt:[19,88],loot:[{id:"water",qty:1}],messageKey:"storyLocations.chnpp.scenes.sarcophagusExterior.waterMessage"},
        {id:"chnpp_sarcophagus_food",box:[6,88,15,10],checkAt:[13,93],loot:[{id:"food",qty:1}],messageKey:"storyLocations.chnpp.scenes.sarcophagusExterior.foodMessage"},
        {id:"chnpp_sarcophagus_medkit",box:[21,89,19,9],checkAt:[30,93],loot:[{id:"medkit",qty:1}],messageKey:"storyLocations.chnpp.scenes.sarcophagusExterior.medkitMessage"}
      ]
    },
    sarcophagus_service:{
      image:"chnpp_sarcophagus_service.webp",
      titleKey:"storyLocations.chnpp.scenes.sarcophagusService.title",
      hintKey:"storyLocations.chnpp.scenes.sarcophagusService.hint",
      parent:"sarcophagus_exterior",
      areas:[
        {id:"chnpp_isolation_protocol_4",box:[5,67,46,25],checkAt:[27,79],loot:[{id:"chnpp_isolation_protocol_4",qty:1}],messageKey:"storyLocations.chnpp.scenes.sarcophagusService.protocolMessage"},
        {id:"chnpp_elevator_level12_scheme",box:[43,61,48,31],checkAt:[68,76],loot:[{id:"chnpp_elevator_level12_scheme",qty:1}],messageKey:"storyLocations.chnpp.scenes.sarcophagusService.schemeMessage"},
        {id:"chnpp_sarcophagus_antirad",box:[87,59,9,14],checkAt:[92,65],loot:[{id:"antirad",qty:1}],messageKey:"storyLocations.chnpp.scenes.sarcophagusService.antiradMessage"}
      ]
    },

    underreactor_corridor:{
      image:"chnpp_underreactor_corridor_access_card.webp",
      introKey:"storyIntro.chnpp.underreactor",
      titleKey:"storyLocations.chnpp.scenes.underreactorCorridor.title",
      hintKey:"storyLocations.chnpp.scenes.underreactorCorridor.hint",
      parent:"main",
      areas:[
        {id:"chnpp_access_card_1037",box:[34,70,26,14],checkAt:[47,77],loot:[{id:"chnpp_access_card_1037",qty:1}],messageKey:"storyLocations.chnpp.scenes.underreactorCorridor.cardMessage"},
        {target:"hermetic_gateway",box:[37,20,24,35],marker:[49,38],labelKey:"storyLocations.chnpp.scenes.underreactorCorridor.gateway",requires:["chnpp_access_card_1037"],failKey:"storyLocations.chnpp.scenes.underreactorCorridor.gatewayLocked"},
        {id:"chnpp_underreactor_ammo",box:[67,49,26,12],checkAt:[80,55],loot:[{id:"ammo",qty:18}],messageKey:"storyLocations.chnpp.scenes.underreactorCorridor.ammoMessage"},
        {id:"chnpp_underreactor_medkit",box:[0,70,23,12],checkAt:[11,76],loot:[{id:"medkit",qty:1}],messageKey:"storyLocations.chnpp.scenes.underreactorCorridor.medkitMessage"},
        {id:"chnpp_underreactor_antirad",box:[52,81,27,11],checkAt:[66,86],loot:[{id:"antirad",qty:1}],messageKey:"storyLocations.chnpp.scenes.underreactorCorridor.antiradMessage"}
      ]
    },
    hermetic_gateway:{
      image:"chnpp_underreactor_corridor_hermetic_gateway.webp",
      titleKey:"storyLocations.chnpp.scenes.hermeticGateway.title",
      hintKey:"storyLocations.chnpp.scenes.hermeticGateway.hint",
      parent:"underreactor_corridor",
      areas:[
        {id:"chnpp_airlock_fuse",box:[50,66,34,19],checkAt:[67,75],loot:[{id:"chnpp_airlock_fuse",qty:1}],messageKey:"storyLocations.chnpp.scenes.hermeticGateway.fuseMessage"},
        {id:"chnpp_emergency_open_key",box:[16,67,36,18],checkAt:[34,76],loot:[{id:"chnpp_emergency_open_key",qty:1}],messageKey:"storyLocations.chnpp.scenes.hermeticGateway.keyMessage"},
        {id:"chnpp_gateway_water",box:[1,64,16,17],checkAt:[9,72],loot:[{id:"water",qty:1}],messageKey:"storyLocations.chnpp.scenes.hermeticGateway.waterMessage"},
        {id:"chnpp_gateway_medkit",box:[0,78,24,12],checkAt:[12,84],loot:[{id:"medkit",qty:1}],messageKey:"storyLocations.chnpp.scenes.hermeticGateway.medkitMessage"},
        {id:"chnpp_gateway_antirad",box:[44,82,19,11],checkAt:[53,87],loot:[{id:"antirad",qty:1}],messageKey:"storyLocations.chnpp.scenes.hermeticGateway.antiradMessage"},
        {id:"chnpp_airlock_open",action:true,box:[38,12,36,38],checkAt:[56,31],requires:["chnpp_airlock_fuse","chnpp_emergency_open_key"],failKey:"storyLocations.chnpp.scenes.hermeticGateway.locked",messageKey:"storyLocations.chnpp.scenes.hermeticGateway.openMessage"}
      ]
    },

    object_entrance:{
      image:"chnpp_object_1037_entrance.webp",
      introKey:"storyIntro.chnpp.object1037",
      titleKey:"storyLocations.chnpp.scenes.objectEntrance.title",
      hintKey:"storyLocations.chnpp.scenes.objectEntrance.hint",
      parent:"main",
      areas:[
        {id:"chnpp_transmitter_access_key",box:[68,77,18,12],checkAt:[77,82],loot:[{id:"chnpp_transmitter_access_key",qty:1}],messageKey:"storyLocations.chnpp.scenes.objectEntrance.keyMessage"},
        {target:"object_server_lab",box:[29,28,42,39],marker:[50,47],labelKey:"storyLocations.chnpp.scenes.objectEntrance.enter",requires:["chnpp_transmitter_access_key"],failKey:"storyLocations.chnpp.scenes.objectEntrance.locked"}
      ]
    },
    object_server_lab:{
      image:"chnpp_object_1037_server_lab.webp",
      titleKey:"storyLocations.chnpp.scenes.objectServerLab.title",
      hintKey:"storyLocations.chnpp.scenes.objectServerLab.hint",
      parent:"object_entrance",
      areas:[
        {id:"chnpp_final_protocol_1037",box:[27,57,31,24],checkAt:[43,69],loot:[{id:"chnpp_final_protocol_1037",qty:1}],messageKey:"storyLocations.chnpp.scenes.objectServerLab.protocolMessage"},
        {id:"chnpp_object_personnel_list",box:[59,58,30,23],checkAt:[74,69],loot:[{id:"chnpp_object_personnel_list",qty:1}],messageKey:"storyLocations.chnpp.scenes.objectServerLab.personnelMessage"}
      ]
    },

    signal_power:{
      image:"chnpp_signal_source_power_module.webp",
      introKey:"storyIntro.chnpp.signalSource",
      titleKey:"storyLocations.chnpp.scenes.signalPower.title",
      hintKey:"storyLocations.chnpp.scenes.signalPower.hint",
      parent:"main",
      areas:[
        {id:"chnpp_power_module_1037",box:[43,64,40,20],checkAt:[62,74],loot:[{id:"chnpp_power_module_1037",qty:1}],messageKey:"storyLocations.chnpp.scenes.signalPower.moduleMessage"},
        {id:"chnpp_transmitter_powered",action:true,box:[72,43,26,22],checkAt:[85,54],requires:["chnpp_power_module_1037"],failKey:"storyLocations.chnpp.scenes.signalPower.powerLocked",messageKey:"storyLocations.chnpp.scenes.signalPower.powerMessage"},
        {target:"signal_console",box:[47,42,20,22],marker:[57,53],labelKey:"storyLocations.chnpp.scenes.signalPower.console",requires:["chnpp_transmitter_powered"],failKey:"storyLocations.chnpp.scenes.signalPower.consoleLocked"}
      ]
    },
    signal_console:{
      image:"chnpp_signal_source_central_console.webp",
      titleKey:"storyLocations.chnpp.scenes.signalConsole.title",
      hintKey:"storyLocations.chnpp.scenes.signalConsole.hint",
      parent:"signal_power",
      areas:[
        {id:"chnpp_operator_authorization_key",box:[15,71,25,14],checkAt:[27,78],loot:[{id:"chnpp_operator_authorization_key",qty:1}],messageKey:"storyLocations.chnpp.scenes.signalConsole.keyMessage"},
        {id:"chnpp_signal_archive_1037",box:[40,70,27,14],checkAt:[53,77],loot:[{id:"chnpp_signal_archive_1037",qty:1}],messageKey:"storyLocations.chnpp.scenes.signalConsole.archiveMessage"},
        {target:"system_core",box:[39,13,24,24],marker:[51,25],labelKey:"storyLocations.chnpp.scenes.signalConsole.core",requires:["chnpp_operator_authorization_key","chnpp_signal_archive_1037","chnpp_transmitter_powered"],failKey:"storyLocations.chnpp.scenes.signalConsole.coreLocked"}
      ]
    },
    system_core:{
      image:"chnpp_signal_source_system_core.webp",
      titleKey:"storyLocations.chnpp.scenes.systemCore.title",
      hintKey:"storyLocations.chnpp.scenes.systemCore.hint",
      parent:"signal_console",
      areas:[
        {
          id:"chnpp_final_boss",
          box:[28,17,45,52],
          checkAt:[50,44],
          combat:{
            type:"signal",
            level:10,
            boss:true,
            nameKey:"storyLocations.chnpp.enemies.finalBoss",
            image:"assets/expeditions/bosses/boss-10.webp",
            energy:12
          }
        },
        {
          id:"chnpp_core_module_1037",
          box:[39,30,22,35],
          checkAt:[50,47],
          visibleAfter:["chnpp_final_boss"],
          loot:[{id:"chnpp_core_module_1037",qty:1}],
          messageKey:"storyLocations.chnpp.scenes.systemCore.coreModuleMessage"
        }
      ]
    }
  }
};
