/* Story location data. */

const DYTIATKY_TEST_EXIT_OPEN = false;

const DYTIATKY_STORY = {
  titleKey:"storyLocations.dytiatky.title",
  descriptionKey:"storyLocations.dytiatky.description",
  questKey:"storyLocations.dytiatky.quest",
  objectiveKey:"storyLocations.dytiatky.objective",
  rewardKey:"storyLocations.dytiatky.reward",
  rewardData:{xp:100,money:150,items:[{id:"ammo",qty:10}]},
  required:["guard_log","gate_key","route_map","toolkit","vehicle_pass","signal_photo","barrel_water","barrel_dosimeter","barrier_open","dytiatky_gate_boss","exit_zone"],
  quests:[
    {requirements:["guard_log"],labelKey:"storyLocations.dytiatky.quests.q1"},
    {requirements:["gate_key"],labelKey:"storyLocations.dytiatky.quests.q2"},
    {requirements:["route_map"],labelKey:"storyLocations.dytiatky.quests.q3"},
    {requirements:["toolkit"],labelKey:"storyLocations.dytiatky.quests.q4"},
    {requirements:["vehicle_pass"],labelKey:"storyLocations.dytiatky.quests.q5"},
    {requirements:["signal_photo"],labelKey:"storyLocations.dytiatky.quests.q6"},
    {requirements:["barrel_water"],labelKey:"storyLocations.dytiatky.quests.q7"},
    {requirements:["barrel_dosimeter"],labelKey:"storyLocations.dytiatky.quests.q8"},
    {requirements:["barrier_open"],labelKey:"storyLocations.dytiatky.quests.q9"},
    {requirements:["dytiatky_gate_boss"],labelKey:"storyLocations.dytiatky.quests.q10"},
    {requirements:["exit_zone"],labelKey:"storyLocations.dytiatky.quests.q11"}
  ],
  scenes:{
    main:{
      image:"dytiatky-main.webp",
      introKey:"storyIntro.dytiatky.main",
      titleKey:"storyLocations.dytiatky.scenes.main.title",
      hintKey:"storyLocations.dytiatky.scenes.main.hint",
      areas:[
        {id:"go_guard",box:[0,33,25,25],target:"guard"},
        {id:"go_car",box:[26,39,25,26],target:"car"},
        {id:"go_barrel",box:[0,58,19,16],target:"barrel"}
      ]
    },
    guard:{
      image:"dytiatky-guard.webp",
      titleKey:"storyLocations.dytiatky.scenes.guard.title",
      hintKey:"storyLocations.dytiatky.scenes.guard.hint",
      parent:"main",
      areas:[
        {id:"guard_log",box:[67,62,23,13],checkAt:[79,68],messageKey:"storyLocations.dytiatky.scenes.guard.guardLogMessage"},
        {id:"gate_key",box:[56,66,10,8],checkAt:[62,70],messageKey:"storyLocations.dytiatky.scenes.guard.gateKeyMessage"},
        {id:"route_map",box:[31,54,30,12],checkAt:[42,59],messageKey:"storyLocations.dytiatky.scenes.guard.routeMapMessage"},
        {id:"radio_frequency",box:[63,50,15,10],checkAt:[70,55],messageKey:"storyLocations.dytiatky.scenes.guard.radioMessage"}
      ]
    },
    car:{
      image:"dytiatky-car-interior.webp",
      titleKey:"storyLocations.dytiatky.scenes.car.title",
      hintKey:"storyLocations.dytiatky.scenes.car.hint",
      parent:"main",
      areas:[
        {id:"toolkit",box:[67,77,25,16],checkAt:[79,84],loot:[{id:"toolkit",qty:1}],messageKey:"storyLocations.dytiatky.scenes.car.toolkitMessage"},
        {id:"go_glovebox",box:[49,34,34,19],target:"glovebox"}
      ]
    },
    glovebox:{
      image:"dytiatky-glovebox.webp",
      titleKey:"storyLocations.dytiatky.scenes.glovebox.title",
      hintKey:"storyLocations.dytiatky.scenes.glovebox.hint",
      parent:"car",
      areas:[
        {id:"vehicle_pass",box:[33,39,23,14],checkAt:[45,46],messageKey:"storyLocations.dytiatky.scenes.glovebox.vehiclePassMessage"},
        {id:"signal_photo",box:[68,44,9,10],checkAt:[72,49],messageKey:"storyLocations.dytiatky.scenes.glovebox.signalPhotoMessage"},
        {id:"flashlight",box:[57,49,11,9],checkAt:[62,53],loot:[{id:"flashlight",qty:1}],messageKey:"storyLocations.dytiatky.scenes.glovebox.flashlightMessage"}
      ]
    },
    barrel:{
      image:"dytiatky-barrel.webp",
      titleKey:"storyLocations.dytiatky.scenes.barrel.title",
      hintKey:"storyLocations.dytiatky.scenes.barrel.hint",
      parent:"main",
      areas:[
        {id:"barrel_medkit",box:[44,23,30,18],checkAt:[59,32],loot:[{id:"medkit",qty:1}],messageKey:"storyLocations.dytiatky.scenes.barrel.medkitMessage"},
        {id:"barrel_food",box:[27,40,17,13],checkAt:[35,47],loot:[{id:"food",qty:1}],messageKey:"storyLocations.dytiatky.scenes.barrel.foodMessage"},
        {id:"barrel_water",box:[67,39,18,22],checkAt:[76,50],loot:[{id:"water",qty:1}],messageKey:"storyLocations.dytiatky.scenes.barrel.waterMessage"},
        {id:"barrel_dosimeter",box:[44,52,13,14],checkAt:[51,59],loot:[{id:"basic_dosimeter",qty:1,rarity:"uncommon",upgradeLevel:1}],messageKey:"storyLocations.dytiatky.scenes.barrel.dosimeterMessage"},
        {id:"barrel_diary",box:[12,55,30,20],checkAt:[27,64],messageKey:"storyLocations.dytiatky.scenes.barrel.diaryMessage"},
        {id:"barrel_zone_map",box:[57,65,26,18],checkAt:[69,75],messageKey:"storyLocations.dytiatky.scenes.barrel.zoneMapMessage"},
        {id:"barrel_flashlight_broken",box:[41,67,15,13],checkAt:[49,73],messageKey:"storyLocations.dytiatky.scenes.barrel.brokenFlashlightMessage"},
        {id:"barrel_ammo",box:[45,44,23,7],checkAt:[56,47],loot:[{id:"ammo",qty:8}],messageKey:"storyLocations.dytiatky.scenes.barrel.ammoMessage"}
      ]
    }
  }
};
