/* Story location data. */

const PRIPYAT_STORY = {
  titleKey:"storyLocations.pripyat.title",
  descriptionKey:"storyLocations.pripyat.description",
  questKey:"storyLocations.pripyat.quest",
  objectiveKey:"storyLocations.pripyat.objective",
  rewardKey:"storyLocations.pripyat.reward",
  rewardData:{xp:260,money:500,items:[{id:"medkit",qty:2},{id:"bandage",qty:3}],equipmentRarity:"uncommon",equipmentRareChance:25},
  required:["pripyat_city_map","school_diary","park_maintenance_log","hotel_signal_note","residential_letter","department_manifest","cinema_frequency_note","bus_passenger_list","hospital_case_file","pripyat_signal_coordinates"],
  quests:[
    {requirements:["pripyat_city_map"],labelKey:"storyLocations.pripyat.quests.q1"},
    {requirements:["school_diary"],labelKey:"storyLocations.pripyat.quests.q2"},
    {requirements:["park_maintenance_log"],labelKey:"storyLocations.pripyat.quests.q3"},
    {requirements:["hotel_signal_note"],labelKey:"storyLocations.pripyat.quests.q4"},
    {requirements:["residential_letter"],labelKey:"storyLocations.pripyat.quests.q5"},
    {requirements:["department_manifest"],labelKey:"storyLocations.pripyat.quests.q6"},
    {requirements:["cinema_frequency_note"],labelKey:"storyLocations.pripyat.quests.q7"},
    {requirements:["bus_passenger_list"],labelKey:"storyLocations.pripyat.quests.q8"},
    {requirements:["hospital_case_file"],labelKey:"storyLocations.pripyat.quests.q9"},
    {requirements:["pripyat_signal_coordinates"],labelKey:"storyLocations.pripyat.quests.q10"}
  ],
  scenes:{
    main:{
      image:"prypiat-main-map.webp",
      introKey:"storyIntro.pripyat.main",
      titleKey:"storyLocations.pripyat.scenes.main.title",
      hintKey:"storyLocations.pripyat.scenes.main.hint",
      areas:[
        {target:"bridge",box:[4,72,22,14],marker:[14,79],labelKey:"storyLocations.pripyat.scenes.main.bridge"},
        {target:"school_entrance",box:[52,17,17,15],marker:[60,23],labelKey:"storyLocations.pripyat.scenes.main.school"},
        {target:"park_entrance",box:[78,19,20,24],marker:[88,31],labelKey:"storyLocations.pripyat.scenes.main.park"},
        {target:"hotel_exterior",box:[2,28,18,20],marker:[12,31],labelKey:"storyLocations.pripyat.scenes.main.hotel"},
        {target:"residential",box:[29,32,23,16],marker:[42,36],labelKey:"storyLocations.pripyat.scenes.main.residential"},
        {target:"department_exterior",box:[55,38,22,17],marker:[68,42],labelKey:"storyLocations.pripyat.scenes.main.department"},
        {target:"cinema_exterior",box:[6,49,24,17],marker:[20,51],labelKey:"storyLocations.pripyat.scenes.main.cinema"},
        {target:"bus_exterior",box:[31,58,28,18],marker:[43,61],labelKey:"storyLocations.pripyat.scenes.main.bus"},
        {target:"hospital_exterior",box:[79,51,20,22],marker:[86,60],labelKey:"storyLocations.pripyat.scenes.main.hospital"},
        {
          id:"pripyat_signal_coordinates",
          box:[43,5,20,10],
          marker:[53,10],
          labelKey:"storyLocations.pripyat.scenes.main.exit",
          visibleAfter:["pripyat_city_map","school_diary","park_maintenance_log","hotel_signal_note","residential_letter","department_manifest","cinema_frequency_note","bus_passenger_list","hospital_case_file"],
          stageTarget:"redforest",
          titleKey:"storyLocations.pripyat.scenes.main.signalTitle",
          icon:"📡",
          descriptionKey:"storyLocations.pripyat.scenes.main.signalDescription",
          messageKey:"storyLocations.pripyat.scenes.main.signalMessage",
          loot:[{id:"pripyat_signal_coordinates",qty:1}]
        }
      ]
    },
    bridge:{
      image:"prypiat-river-bridge.webp",
      introKey:"storyIntro.pripyat.bridge",
      titleKey:"storyLocations.pripyat.scenes.bridge.title",
      hintKey:"storyLocations.pripyat.scenes.bridge.hint",
      parent:"main",
      areas:[
        {
          id:"pripyat_city_map",
          box:[38,69,25,15],
          checkAt:[48,76],
          loot:[{id:"pripyat_city_map",qty:1}],
          titleKey:"storyLocations.pripyat.scenes.bridge.mapTitle",
          icon:"🗺",
          descriptionKey:"storyLocations.pripyat.scenes.bridge.mapDescription",
          messageKey:"storyLocations.pripyat.scenes.bridge.mapMessage"
        },
        {
          id:"bridge_cache",
          box:[64,65,30,24],
          checkAt:[78,74],
          loot:[{id:"ammo",qty:5}],
          messageKey:"storyLocations.pripyat.scenes.bridge.cacheMessage"
        }
      ]
    },
    school_entrance:{
      image:"prypiat-school-2-entrance.webp",
      introKey:"storyIntro.pripyat.school",
      titleKey:"storyLocations.pripyat.scenes.schoolEntrance.title",
      hintKey:"storyLocations.pripyat.scenes.schoolEntrance.hint",
      parent:"main",
      areas:[
        {target:"school_corridor",box:[30,14,50,43],marker:[55,42],labelKey:"storyLocations.pripyat.scenes.schoolEntrance.enter"},
        {
          id:"school_route_note",
          box:[64,76,31,18],
          checkAt:[80,82],
          titleKey:"storyLocations.pripyat.scenes.schoolEntrance.noteTitle",
          icon:"📄",
          descriptionKey:"storyLocations.pripyat.scenes.schoolEntrance.noteDescription",
          messageKey:"storyLocations.pripyat.scenes.schoolEntrance.noteMessage"
        }
      ]
    },
    school_corridor:{
      image:"prypiat-school-2-corridor.webp",
      titleKey:"storyLocations.pripyat.scenes.schoolCorridor.title",
      hintKey:"storyLocations.pripyat.scenes.schoolCorridor.hint",
      parent:"school_entrance",
      areas:[
        {target:"school_cabinet",box:[0,10,34,49],marker:[18,37],labelKey:"storyLocations.pripyat.scenes.schoolCorridor.cabinet"},
        {target:"school_stairwell",box:[35,7,37,49],marker:[53,28],labelKey:"storyLocations.pripyat.scenes.schoolCorridor.stairs"}
      ]
    },
    school_cabinet:{
      image:"prypiat_school_corridor_cabinet_15.webp",
      titleKey:"storyLocations.pripyat.scenes.schoolCabinet.title",
      hintKey:"storyLocations.pripyat.scenes.schoolCabinet.hint",
      parent:"school_corridor",
      areas:[
        {
          target:"school_classroom",
          box:[52,8,29,45],
          marker:[66,31],
          labelKey:"storyLocations.pripyat.scenes.schoolCabinet.enter",
          requires:["school_room_key"],
          failKey:"storyLocations.pripyat.scenes.schoolCabinet.locked"
        },
        {
          id:"school_room_key",
          box:[57,72,34,21],
          checkAt:[76,79],
          titleKey:"storyLocations.pripyat.scenes.schoolCabinet.keyTitle",
          icon:"🗝",
          descriptionKey:"storyLocations.pripyat.scenes.schoolCabinet.keyDescription",
          messageKey:"storyLocations.pripyat.scenes.schoolCabinet.keyMessage"
        }
      ]
    },
    school_stairwell:{
      image:"prypiat-school-2-stairwell.webp",
      titleKey:"storyLocations.pripyat.scenes.schoolStairwell.title",
      hintKey:"storyLocations.pripyat.scenes.schoolStairwell.hint",
      parent:"school_corridor",
      areas:[
        {
          id:"school_bandage",
          box:[60,76,31,19],
          checkAt:[77,82],
          loot:[{id:"bandage",qty:1}],
          messageKey:"storyLocations.pripyat.scenes.schoolStairwell.bandageMessage"
        }
      ]
    },
    school_classroom:{
      image:"prypiat-school-2-classroom-15.webp",
      titleKey:"storyLocations.pripyat.scenes.schoolClassroom.title",
      hintKey:"storyLocations.pripyat.scenes.schoolClassroom.hint",
      parent:"school_cabinet",
      areas:[
        {
          id:"school_diary",
          box:[40,70,34,24],
          checkAt:[57,77],
          loot:[{id:"school_diary",qty:1}],
          titleKey:"storyLocations.pripyat.scenes.schoolClassroom.diaryTitle",
          icon:'<img src="assets/inventory-items/quest_document.webp" alt="">',
          descriptionKey:"storyLocations.pripyat.scenes.schoolClassroom.diaryDescription",
          messageKey:"storyLocations.pripyat.scenes.schoolClassroom.diaryMessage"
        }
      ]
    },
    park_entrance:{
      image:"prypiat-amusement-park-entrance.webp",
      introKey:"storyIntro.pripyat.park",
      titleKey:"storyLocations.pripyat.scenes.parkEntrance.title",
      hintKey:"storyLocations.pripyat.scenes.parkEntrance.hint",
      parent:"main",
      areas:[
        {target:"park_wheel",box:[47,9,45,55],marker:[76,31],labelKey:"storyLocations.pripyat.scenes.parkEntrance.wheel"},
        {
          id:"park_ticket",
          box:[24,72,39,19],
          checkAt:[43,79],
          titleKey:"storyLocations.pripyat.scenes.parkEntrance.ticketTitle",
          icon:'<img src="assets/inventory-items/quest_tickets.webp" alt="">',
          descriptionKey:"storyLocations.pripyat.scenes.parkEntrance.ticketDescription",
          messageKey:"storyLocations.pripyat.scenes.parkEntrance.ticketMessage"
        }
      ]
    },
    park_wheel:{
      image:"prypiat-amusement-park-ferris-wheel.webp",
      titleKey:"storyLocations.pripyat.scenes.parkWheel.title",
      hintKey:"storyLocations.pripyat.scenes.parkWheel.hint",
      parent:"park_entrance",
      areas:[
        {
          id:"park_maintenance_log",
          box:[20,74,34,18],
          checkAt:[37,80],
          loot:[{id:"park_maintenance_log",qty:1}],
          titleKey:"storyLocations.pripyat.scenes.parkWheel.logTitle",
          icon:"📒",
          descriptionKey:"storyLocations.pripyat.scenes.parkWheel.logDescription",
          messageKey:"storyLocations.pripyat.scenes.parkWheel.logMessage"
        }
      ]
    },
    hotel_exterior:{
      image:"prypiat-hotel-polissia-exterior.webp",
      introKey:"storyIntro.pripyat.hotel",
      titleKey:"storyLocations.pripyat.scenes.hotelExterior.title",
      hintKey:"storyLocations.pripyat.scenes.hotelExterior.hint",
      parent:"main",
      areas:[
        {target:"hotel_lobby",box:[31,34,39,38],marker:[51,61],labelKey:"storyLocations.pripyat.scenes.hotelExterior.enter"},
        {
          id:"hotel_medkit",
          box:[3,78,36,19],
          checkAt:[20,84],
          loot:[{id:"medkit",qty:1}],
          messageKey:"storyLocations.pripyat.scenes.hotelExterior.medkitMessage"
        }
      ]
    },
    hotel_lobby:{
      image:"prypiat-hotel-polissia-lobby.webp",
      titleKey:"storyLocations.pripyat.scenes.hotelLobby.title",
      hintKey:"storyLocations.pripyat.scenes.hotelLobby.hint",
      parent:"hotel_exterior",
      areas:[
        {
          id:"hotel_guestbook",
          box:[35,73,31,20],
          checkAt:[51,79],
          titleKey:"storyLocations.pripyat.scenes.hotelLobby.logTitle",
          icon:"📖",
          descriptionKey:"storyLocations.pripyat.scenes.hotelLobby.logDescription",
          messageKey:"storyLocations.pripyat.scenes.hotelLobby.logMessage"
        },
        {
          id:"hotel_room_key",
          box:[67,72,28,18],
          checkAt:[82,77],
          titleKey:"storyLocations.pripyat.scenes.hotelLobby.keyTitle",
          icon:"🗝",
          descriptionKey:"storyLocations.pripyat.scenes.hotelLobby.keyDescription",
          messageKey:"storyLocations.pripyat.scenes.hotelLobby.keyMessage"
        },
        {
          target:"hotel_corridor",
          box:[7,10,42,49],
          marker:[27,37],
          labelKey:"storyLocations.pripyat.scenes.hotelLobby.rooms",
          requires:["hotel_guestbook","hotel_room_key"],
          failKey:"storyLocations.pripyat.scenes.hotelLobby.roomsLocked"
        }
      ]
    },
    hotel_corridor:{
      image:"prypiat-hotel-polissia-corridor.webp",
      titleKey:"storyLocations.pripyat.scenes.hotelCorridor.title",
      hintKey:"storyLocations.pripyat.scenes.hotelCorridor.hint",
      parent:"hotel_lobby",
      areas:[
        {
          target:"hotel_room",
          box:[65,10,32,55],
          marker:[80,39],
          labelKey:"storyLocations.pripyat.scenes.hotelCorridor.room",
          requires:["hotel_room_key"],
          failKey:"storyLocations.pripyat.scenes.hotelCorridor.roomLocked"
        },
        {
          id:"hotel_battery",
          box:[3,63,35,24],
          checkAt:[21,72],
          loot:[{id:"battery",qty:1}],
          messageKey:"storyLocations.pripyat.scenes.hotelCorridor.batteryMessage"
        }
      ]
    },
    hotel_room:{
      image:"prypiat-hotel-polissia-room.webp",
      titleKey:"storyLocations.pripyat.scenes.hotelRoom.title",
      hintKey:"storyLocations.pripyat.scenes.hotelRoom.hint",
      parent:"hotel_corridor",
      areas:[
        {
          id:"hotel_signal_note",
          box:[76,35,22,34],
          checkAt:[86,48],
          loot:[{id:"hotel_signal_note",qty:1}],
          titleKey:"storyLocations.pripyat.scenes.hotelRoom.noteTitle",
          icon:"📻",
          descriptionKey:"storyLocations.pripyat.scenes.hotelRoom.noteDescription",
          messageKey:"storyLocations.pripyat.scenes.hotelRoom.noteMessage"
        }
      ]
    },
    residential:{
      image:"pripyat_residential_building.webp",
      introKey:"storyIntro.pripyat.residential",
      titleKey:"storyLocations.pripyat.scenes.residential.title",
      hintKey:"storyLocations.pripyat.scenes.residential.hint",
      parent:"main",
      areas:[
        {
          id:"residential_letter",
          box:[39,72,38,20],
          checkAt:[57,78],
          loot:[{id:"residential_letter",qty:1}],
          titleKey:"storyLocations.pripyat.scenes.residential.letterTitle",
          icon:"✉",
          descriptionKey:"storyLocations.pripyat.scenes.residential.letterDescription",
          messageKey:"storyLocations.pripyat.scenes.residential.letterMessage"
        },
        {
          id:"residential_keys",
          box:[68,55,26,18],
          checkAt:[81,62],
          titleKey:"storyLocations.pripyat.scenes.residential.keysTitle",
          icon:"🗝",
          descriptionKey:"storyLocations.pripyat.scenes.residential.keysDescription",
          messageKey:"storyLocations.pripyat.scenes.residential.keysMessage"
        }
      ]
    },
    department_exterior:{
      image:"pripyat_department_store.webp",
      introKey:"storyIntro.pripyat.department",
      titleKey:"storyLocations.pripyat.scenes.departmentExterior.title",
      hintKey:"storyLocations.pripyat.scenes.departmentExterior.hint",
      parent:"main",
      areas:[
        {target:"department_car",box:[69,34,28,22],marker:[83,46],labelKey:"storyLocations.pripyat.scenes.departmentExterior.car"},
        {target:"department_interior",box:[28,14,39,42],marker:[51,45],labelKey:"storyLocations.pripyat.scenes.departmentExterior.enter"},
        {
          id:"department_cache",
          box:[59,68,38,22],
          checkAt:[78,75],
          loot:[{id:"food",qty:2},{id:"water",qty:1}],
          messageKey:"storyLocations.pripyat.scenes.departmentExterior.cacheMessage"
        }
      ]
    },
    department_car:{
      image:"pripyat_department_store_car_interior.webp",
      titleKey:"storyLocations.pripyat.scenes.departmentCar.title",
      hintKey:"storyLocations.pripyat.scenes.departmentCar.hint",
      parent:"department_exterior",
      areas:[
        {
          id:"department_delivery_note",
          box:[25,61,51,28],
          checkAt:[48,70],
          titleKey:"storyLocations.pripyat.scenes.departmentCar.noteTitle",
          icon:"📄",
          descriptionKey:"storyLocations.pripyat.scenes.departmentCar.noteDescription",
          messageKey:"storyLocations.pripyat.scenes.departmentCar.noteMessage"
        }
      ]
    },
    department_interior:{
      image:"pripyat_department_store_interior.webp",
      titleKey:"storyLocations.pripyat.scenes.departmentInterior.title",
      hintKey:"storyLocations.pripyat.scenes.departmentInterior.hint",
      parent:"department_exterior",
      areas:[
        {
          id:"department_manifest",
          box:[38,70,39,23],
          checkAt:[60,77],
          loot:[{id:"department_manifest",qty:1}],
          titleKey:"storyLocations.pripyat.scenes.departmentInterior.manifestTitle",
          icon:"📋",
          descriptionKey:"storyLocations.pripyat.scenes.departmentInterior.manifestDescription",
          messageKey:"storyLocations.pripyat.scenes.departmentInterior.manifestMessage"
        },
        {
          id:"department_filter",
          box:[79,69,19,17],
          checkAt:[89,74],
          loot:[{id:"filter",qty:1}],
          messageKey:"storyLocations.pripyat.scenes.departmentInterior.filterMessage"
        }
      ]
    },
    cinema_exterior:{
      image:"pripyat_cinema_prometheus_exterior.webp",
      introKey:"storyIntro.pripyat.cinema",
      titleKey:"storyLocations.pripyat.scenes.cinemaExterior.title",
      hintKey:"storyLocations.pripyat.scenes.cinemaExterior.hint",
      parent:"main",
      areas:[
        {target:"cinema_car",box:[0,42,35,22],marker:[22,51],labelKey:"storyLocations.pripyat.scenes.cinemaExterior.car"},
        {target:"cinema_interior",box:[38,25,38,30],marker:[55,45],labelKey:"storyLocations.pripyat.scenes.cinemaExterior.enter"},
        {
          id:"cinema_reel",
          box:[38,72,30,19],
          checkAt:[53,79],
          titleKey:"storyLocations.pripyat.scenes.cinemaExterior.reelTitle",
          icon:"🎞",
          descriptionKey:"storyLocations.pripyat.scenes.cinemaExterior.reelDescription",
          messageKey:"storyLocations.pripyat.scenes.cinemaExterior.reelMessage"
        }
      ]
    },
    cinema_car:{
      image:"cinema_prometey_car_interior.webp",
      titleKey:"storyLocations.pripyat.scenes.cinemaCar.title",
      hintKey:"storyLocations.pripyat.scenes.cinemaCar.hint",
      parent:"cinema_exterior",
      areas:[
        {target:"cinema_glovebox",box:[55,32,43,28],marker:[77,48],labelKey:"storyLocations.pripyat.scenes.cinemaCar.glovebox"},
        {
          id:"cinema_pass",
          box:[20,68,51,23],
          checkAt:[45,75],
          titleKey:"storyLocations.pripyat.scenes.cinemaCar.passTitle",
          icon:"🎫",
          descriptionKey:"storyLocations.pripyat.scenes.cinemaCar.passDescription",
          messageKey:"storyLocations.pripyat.scenes.cinemaCar.passMessage"
        }
      ]
    },
    cinema_glovebox:{
      image:"cinema_prometey_glovebox.webp",
      titleKey:"storyLocations.pripyat.scenes.cinemaGlovebox.title",
      hintKey:"storyLocations.pripyat.scenes.cinemaGlovebox.hint",
      parent:"cinema_car",
      areas:[
        {
          id:"cinema_frequency_note",
          box:[18,52,61,33],
          checkAt:[49,63],
          loot:[{id:"cinema_frequency_note",qty:1}],
          titleKey:"storyLocations.pripyat.scenes.cinemaGlovebox.noteTitle",
          icon:"📻",
          descriptionKey:"storyLocations.pripyat.scenes.cinemaGlovebox.noteDescription",
          messageKey:"storyLocations.pripyat.scenes.cinemaGlovebox.noteMessage"
        }
      ]
    },
    cinema_interior:{
      image:"pripyat_cinema_prometheus_interior_quest.webp",
      titleKey:"storyLocations.pripyat.scenes.cinemaInterior.title",
      hintKey:"storyLocations.pripyat.scenes.cinemaInterior.hint",
      parent:"cinema_exterior",
      areas:[
        {
          id:"cinema_archive",
          box:[18,65,57,27],
          checkAt:[47,74],
          titleKey:"storyLocations.pripyat.scenes.cinemaInterior.archiveTitle",
          icon:"📚",
          descriptionKey:"storyLocations.pripyat.scenes.cinemaInterior.archiveDescription",
          messageKey:"storyLocations.pripyat.scenes.cinemaInterior.archiveMessage"
        }
      ]
    },
    bus_exterior:{
      image:"pripyat_bus_station_exterior.webp",
      introKey:"storyIntro.pripyat.bus",
      titleKey:"storyLocations.pripyat.scenes.busExterior.title",
      hintKey:"storyLocations.pripyat.scenes.busExterior.hint",
      parent:"main",
      areas:[
        {target:"bus_vehicle",box:[0,28,30,20],marker:[20,40],labelKey:"storyLocations.pripyat.scenes.busExterior.bus"},
        {target:"bus_interior",box:[33,13,55,21],marker:[59,32],labelKey:"storyLocations.pripyat.scenes.busExterior.station"},
        {target:"bus_zhiguli",box:[48,35,28,17],marker:[63,44],labelKey:"storyLocations.pripyat.scenes.busExterior.zhiguli"},
        {
          id:"bus_ticket_bundle",
          box:[5,66,47,23],
          checkAt:[27,75],
          titleKey:"storyLocations.pripyat.scenes.busExterior.ticketsTitle",
          icon:'<img src="assets/inventory-items/quest_tickets.webp" alt="">',
          descriptionKey:"storyLocations.pripyat.scenes.busExterior.ticketsDescription",
          messageKey:"storyLocations.pripyat.scenes.busExterior.ticketsMessage"
        }
      ]
    },
    bus_vehicle:{
      image:"pripyat_bus_interior.webp",
      titleKey:"storyLocations.pripyat.scenes.busVehicle.title",
      hintKey:"storyLocations.pripyat.scenes.busVehicle.hint",
      parent:"bus_exterior",
      areas:[
        {
          id:"bus_passenger_list",
          box:[10,67,48,25],
          checkAt:[32,76],
          loot:[{id:"bus_passenger_list",qty:1}],
          titleKey:"storyLocations.pripyat.scenes.busVehicle.listTitle",
          icon:"📋",
          descriptionKey:"storyLocations.pripyat.scenes.busVehicle.listDescription",
          messageKey:"storyLocations.pripyat.scenes.busVehicle.listMessage"
        },
        {
          id:"bus_water",
          box:[62,77,31,16],
          checkAt:[78,82],
          loot:[{id:"water",qty:1}],
          messageKey:"storyLocations.pripyat.scenes.busVehicle.waterMessage"
        }
      ]
    },
    bus_interior:{
      image:"pripyat_bus_station_interior_quest.webp",
      titleKey:"storyLocations.pripyat.scenes.busInterior.title",
      hintKey:"storyLocations.pripyat.scenes.busInterior.hint",
      parent:"bus_exterior",
      areas:[
        {
          id:"bus_dispatch_map",
          box:[17,63,55,26],
          checkAt:[44,72],
          titleKey:"storyLocations.pripyat.scenes.busInterior.mapTitle",
          icon:"🗺",
          descriptionKey:"storyLocations.pripyat.scenes.busInterior.mapDescription",
          messageKey:"storyLocations.pripyat.scenes.busInterior.mapMessage"
        }
      ]
    },
    bus_zhiguli:{
      image:"pripyat_zhiguli_interior.webp",
      titleKey:"storyLocations.pripyat.scenes.busZhiguli.title",
      hintKey:"storyLocations.pripyat.scenes.busZhiguli.hint",
      parent:"bus_exterior",
      areas:[
        {
          id:"bus_driver_pass",
          box:[8,67,52,24],
          checkAt:[31,75],
          titleKey:"storyLocations.pripyat.scenes.busZhiguli.passTitle",
          icon:"🪪",
          descriptionKey:"storyLocations.pripyat.scenes.busZhiguli.passDescription",
          messageKey:"storyLocations.pripyat.scenes.busZhiguli.passMessage"
        }
      ]
    },
    hospital_exterior:{
      image:"pripyat_hospital_exterior.webp",
      introKey:"storyIntro.pripyat.hospital",
      titleKey:"storyLocations.pripyat.scenes.hospitalExterior.title",
      hintKey:"storyLocations.pripyat.scenes.hospitalExterior.hint",
      parent:"main",
      areas:[
        {target:"hospital_ambulance",box:[0,38,34,28],marker:[17,54],labelKey:"storyLocations.pripyat.scenes.hospitalExterior.ambulance"},
        {target:"hospital_interior",box:[32,31,43,28],marker:[53,47],labelKey:"storyLocations.pripyat.scenes.hospitalExterior.enter"}
      ]
    },
    hospital_ambulance:{
      image:"pripyat_ambulance_interior.webp",
      titleKey:"storyLocations.pripyat.scenes.hospitalAmbulance.title",
      hintKey:"storyLocations.pripyat.scenes.hospitalAmbulance.hint",
      parent:"hospital_exterior",
      areas:[
        {
          id:"hospital_ambulance_medkit",
          box:[4,40,55,30],
          checkAt:[30,51],
          loot:[{id:"medkit",qty:1}],
          messageKey:"storyLocations.pripyat.scenes.hospitalAmbulance.medkitMessage"
        },
        {
          id:"hospital_medical_card",
          box:[68,81,25,13],
          checkAt:[80,85],
          titleKey:"storyLocations.pripyat.scenes.hospitalAmbulance.cardTitle",
          icon:"📄",
          descriptionKey:"storyLocations.pripyat.scenes.hospitalAmbulance.cardDescription",
          messageKey:"storyLocations.pripyat.scenes.hospitalAmbulance.cardMessage"
        }
      ]
    },
    hospital_interior:{
      image:"pripyat_hospital_interior.webp",
      titleKey:"storyLocations.pripyat.scenes.hospitalInterior.title",
      hintKey:"storyLocations.pripyat.scenes.hospitalInterior.hint",
      parent:"hospital_exterior",
      areas:[
        {
          id:"hospital_case_file",
          box:[4,66,45,13],
          checkAt:[25,73],
          loot:[{id:"hospital_case_file",qty:1}],
          titleKey:"storyLocations.pripyat.scenes.hospitalInterior.caseTitle",
          icon:"🩺",
          descriptionKey:"storyLocations.pripyat.scenes.hospitalInterior.caseDescription",
          messageKey:"storyLocations.pripyat.scenes.hospitalInterior.caseMessage"
        },
        {
          id:"hospital_access_badge",
          box:[12,79,27,12],
          checkAt:[23,85],
          titleKey:"storyLocations.pripyat.scenes.hospitalInterior.badgeTitle",
          icon:"🪪",
          descriptionKey:"storyLocations.pripyat.scenes.hospitalInterior.badgeDescription",
          messageKey:"storyLocations.pripyat.scenes.hospitalInterior.badgeMessage"
        },
        {
          id:"hospital_iodine",
          box:[80,61,12,11],
          checkAt:[86,66],
          loot:[{id:"iodine",qty:1}],
          titleKey:"survival.hospital.iodineTitle",
          icon:"☢",
          descriptionKey:"survival.hospital.iodineDescription",
          messageKey:"survival.hospital.iodineFound"
        },
        {
          service:"hospitalDecontamination",
          box:[67,19,31,37],
          marker:[84,37],
          labelKey:"survival.hospital.serviceLabel"
        }
      ]
    }
  }
};
