/* Story location data. */

const YANIV_STORY = {
  titleKey:"storyLocations.yaniv.title",
  descriptionKey:"storyLocations.yaniv.description",
  questKey:"storyLocations.yaniv.quest",
  objectiveKey:"storyLocations.yaniv.objective",
  rewardKey:"storyLocations.yaniv.reward",
  rewardData:{xp:410,money:450,items:[{id:"ammo",qty:20},{id:"medkit",qty:1}],equipmentRarity:"epic"},
  required:[
    "yaniv_checkpoint_register",
    "yaniv_station_documents",
    "yaniv_service_token",
    "yaniv_emergency_route_map",
    "yaniv_cargo_cache",
    "yaniv_power_restored",
    "yaniv_military_pass",
    "yaniv_route_open"
  ],
  quests:[
    {requirements:["yaniv_checkpoint_register"],labelKey:"storyLocations.yaniv.quests.q1"},
    {requirements:["yaniv_station_documents"],labelKey:"storyLocations.yaniv.quests.q2"},
    {requirements:["yaniv_service_token"],labelKey:"storyLocations.yaniv.quests.q3"},
    {requirements:["yaniv_emergency_route_map"],labelKey:"storyLocations.yaniv.quests.q4"},
    {requirements:["yaniv_cargo_cache"],labelKey:"storyLocations.yaniv.quests.q5"},
    {requirements:["yaniv_power_restored"],labelKey:"storyLocations.yaniv.quests.q6"},
    {requirements:["yaniv_military_pass"],labelKey:"storyLocations.yaniv.quests.q7"},
    {requirements:["yaniv_route_open"],labelKey:"storyLocations.yaniv.quests.q8"}
  ],
  scenes:{
    main:{
      image:"yaniv.webp",
      introKey:"storyIntro.yaniv.main",
      titleKey:"storyLocations.yaniv.scenes.main.title",
      hintKey:"storyLocations.yaniv.scenes.main.hint",
      areas:[
        {target:"checkpoint_outside",box:[7,68,29,18],marker:[21,76],labelKey:"storyLocations.yaniv.scenes.main.checkpoint"},
        {target:"waiting_hall",box:[24,40,26,19],marker:[37,49],labelKey:"storyLocations.yaniv.scenes.main.waiting",requires:["yaniv_checkpoint_register"],failKey:"storyLocations.yaniv.scenes.main.waitingLocked"},
        {target:"platform",box:[52,44,11,22],marker:[58,54],labelKey:"storyLocations.yaniv.scenes.main.platform",requires:["yaniv_station_documents"],failKey:"storyLocations.yaniv.scenes.main.platformLocked"},
        {target:"dispatcher_outside",box:[51,34,19,10],marker:[60,39],labelKey:"storyLocations.yaniv.scenes.main.dispatcher",requires:["yaniv_service_token"],failKey:"storyLocations.yaniv.scenes.main.dispatcherLocked"},
        {target:"cargo_wagon",box:[64,54,16,22],marker:[72,63],labelKey:"storyLocations.yaniv.scenes.main.wagon",requires:["yaniv_emergency_route_map"],failKey:"storyLocations.yaniv.scenes.main.wagonLocked"},
        {target:"electrical_outside",box:[3,51,20,14],marker:[13,57],labelKey:"storyLocations.yaniv.scenes.main.electrical",requires:["yaniv_cargo_cache"],failKey:"storyLocations.yaniv.scenes.main.electricalLocked"},
        {target:"service_post_outside",box:[4,32,19,13],marker:[14,38],labelKey:"storyLocations.yaniv.scenes.main.servicePost",requires:["yaniv_power_restored"],failKey:"storyLocations.yaniv.scenes.main.servicePostLocked"},
        {target:"service_route",box:[78,24,19,17],marker:[88,31],labelKey:"storyLocations.yaniv.scenes.main.route",requires:["yaniv_military_pass"],failKey:"storyLocations.yaniv.scenes.main.routeLocked"}
      ]
    },
    checkpoint_outside:{
      image:"yaniv_checkpoint_outside.webp",
      introKey:"storyIntro.yaniv.checkpoint",
      titleKey:"storyLocations.yaniv.scenes.checkpointOutside.title",
      hintKey:"storyLocations.yaniv.scenes.checkpointOutside.hint",
      parent:"main",
      areas:[
        {target:"checkpoint_inside",box:[28,25,20,25],marker:[38,39],labelKey:"storyLocations.yaniv.scenes.checkpointOutside.enter"},
        {id:"yaniv_checkpoint_medkit",box:[1,57,31,35],checkAt:[16,72],loot:[{id:"medkit",qty:1}],messageKey:"storyLocations.yaniv.scenes.checkpointOutside.medkitMessage"},
        {id:"yaniv_checkpoint_water",box:[37,64,9,18],checkAt:[42,72],loot:[{id:"water",qty:1}],messageKey:"storyLocations.yaniv.scenes.checkpointOutside.waterMessage"},
        {id:"yaniv_checkpoint_ammo",box:[47,77,15,11],checkAt:[54,82],loot:[{id:"ammo",qty:6}],messageKey:"storyLocations.yaniv.scenes.checkpointOutside.ammoMessage"}
      ]
    },
    checkpoint_inside:{
      image:"yaniv_checkpoint_inside.webp",
      titleKey:"storyLocations.yaniv.scenes.checkpointInside.title",
      hintKey:"storyLocations.yaniv.scenes.checkpointInside.hint",
      parent:"checkpoint_outside",
      areas:[
        {id:"yaniv_checkpoint_register",box:[20,68,32,12],checkAt:[36,74],loot:[{id:"yaniv_checkpoint_register",qty:1}],titleKey:"storyLocations.yaniv.scenes.checkpointInside.registerTitle",icon:"📒",descriptionKey:"storyLocations.yaniv.scenes.checkpointInside.registerDescription",messageKey:"storyLocations.yaniv.scenes.checkpointInside.registerMessage"},
        {id:"yaniv_checkpoint_energy",box:[72,59,11,12],checkAt:[77,65],loot:[{id:"food",qty:1}],messageKey:"storyLocations.yaniv.scenes.checkpointInside.energyMessage"}
      ]
    },
    waiting_hall:{
      image:"yaniv_waiting_hall.webp",
      introKey:"storyIntro.yaniv.waiting",
      titleKey:"storyLocations.yaniv.scenes.waitingHall.title",
      hintKey:"storyLocations.yaniv.scenes.waitingHall.hint",
      parent:"main",
      areas:[
        {id:"yaniv_station_documents",box:[26,75,21,13],checkAt:[37,81],loot:[{id:"yaniv_station_documents",qty:1}],titleKey:"storyLocations.yaniv.scenes.waitingHall.documentsTitle",icon:"📁",descriptionKey:"storyLocations.yaniv.scenes.waitingHall.documentsDescription",messageKey:"storyLocations.yaniv.scenes.waitingHall.documentsMessage"},
        {id:"yaniv_waiting_medkit",box:[62,83,17,10],checkAt:[70,87],loot:[{id:"bandage",qty:1}],messageKey:"storyLocations.yaniv.scenes.waitingHall.bandageMessage"},
        {id:"yaniv_waiting_food",box:[48,82,10,9],checkAt:[53,86],loot:[{id:"food",qty:1}],messageKey:"storyLocations.yaniv.scenes.waitingHall.foodMessage"}
      ]
    },
    platform:{
      image:"yaniv_platform.webp",
      introKey:"storyIntro.yaniv.platform",
      titleKey:"storyLocations.yaniv.scenes.platform.title",
      hintKey:"storyLocations.yaniv.scenes.platform.hint",
      parent:"main",
      areas:[
        {id:"yaniv_service_token",box:[16,75,22,13],checkAt:[27,80],loot:[{id:"yaniv_service_token",qty:1}],titleKey:"storyLocations.yaniv.scenes.platform.tokenTitle",icon:"🪙",descriptionKey:"storyLocations.yaniv.scenes.platform.tokenDescription",messageKey:"storyLocations.yaniv.scenes.platform.tokenMessage"},
        {id:"yaniv_platform_medkit",box:[59,84,20,12],checkAt:[69,89],loot:[{id:"medkit",qty:1}],messageKey:"storyLocations.yaniv.scenes.platform.medkitMessage"},
        {id:"yaniv_platform_ammo",box:[47,72,28,10],checkAt:[61,76],loot:[{id:"ammo",qty:5}],messageKey:"storyLocations.yaniv.scenes.platform.ammoMessage"}
      ]
    },
    dispatcher_outside:{
      image:"yaniv_dispatcher_office_outside.webp",
      introKey:"storyIntro.yaniv.dispatcher",
      titleKey:"storyLocations.yaniv.scenes.dispatcherOutside.title",
      hintKey:"storyLocations.yaniv.scenes.dispatcherOutside.hint",
      parent:"main",
      areas:[
        {target:"dispatcher_inside",box:[60,27,24,39],marker:[72,43],labelKey:"storyLocations.yaniv.scenes.dispatcherOutside.enter"},
        {id:"yaniv_dispatcher_journal",box:[45,80,23,12],checkAt:[56,85],titleKey:"storyLocations.yaniv.scenes.dispatcherOutside.journalTitle",icon:"📓",descriptionKey:"storyLocations.yaniv.scenes.dispatcherOutside.journalDescription",messageKey:"storyLocations.yaniv.scenes.dispatcherOutside.journalMessage"}
      ]
    },
    dispatcher_inside:{
      image:"yaniv_dispatcher_office_inside.webp",
      titleKey:"storyLocations.yaniv.scenes.dispatcherInside.title",
      hintKey:"storyLocations.yaniv.scenes.dispatcherInside.hint",
      parent:"dispatcher_outside",
      areas:[
        {id:"yaniv_emergency_route_map",box:[19,47,48,20],checkAt:[43,57],loot:[{id:"yaniv_emergency_route_map",qty:1}],titleKey:"storyLocations.yaniv.scenes.dispatcherInside.routeTitle",icon:"🗺",descriptionKey:"storyLocations.yaniv.scenes.dispatcherInside.routeDescription",messageKey:"storyLocations.yaniv.scenes.dispatcherInside.routeMessage"},
        {id:"yaniv_dispatcher_radio",box:[70,39,22,18],checkAt:[81,47],titleKey:"storyLocations.yaniv.scenes.dispatcherInside.radioTitle",icon:"📻",descriptionKey:"storyLocations.yaniv.scenes.dispatcherInside.radioDescription",messageKey:"storyLocations.yaniv.scenes.dispatcherInside.radioMessage"}
      ]
    },
    cargo_wagon:{
      image:"yaniv_cargo_wagon.webp",
      introKey:"storyIntro.yaniv.cargo",
      titleKey:"storyLocations.yaniv.scenes.cargoWagon.title",
      hintKey:"storyLocations.yaniv.scenes.cargoWagon.hint",
      parent:"main",
      areas:[
        {id:"yaniv_cargo_cache",box:[16,49,29,16],checkAt:[30,56],loot:[{id:"ammo",qty:15},{id:"bandage",qty:1},{id:"food",qty:1}],titleKey:"storyLocations.yaniv.scenes.cargoWagon.cacheTitle",icon:"▥",descriptionKey:"storyLocations.yaniv.scenes.cargoWagon.cacheDescription",messageKey:"storyLocations.yaniv.scenes.cargoWagon.cacheMessage"},
        {id:"yaniv_cargo_water",box:[46,50,12,8],checkAt:[52,53],loot:[{id:"water",qty:1}],messageKey:"storyLocations.yaniv.scenes.cargoWagon.waterMessage"}
      ]
    },
    electrical_outside:{
      image:"yaniv_electrical_room_outside.webp",
      introKey:"storyIntro.yaniv.electrical",
      titleKey:"storyLocations.yaniv.scenes.electricalOutside.title",
      hintKey:"storyLocations.yaniv.scenes.electricalOutside.hint",
      parent:"main",
      areas:[
        {target:"electrical_inside",box:[46,29,21,35],marker:[57,45],labelKey:"storyLocations.yaniv.scenes.electricalOutside.enter"},
        {id:"yaniv_electrical_toolbox",box:[52,64,18,11],checkAt:[61,69],loot:[{id:"scrap",qty:2}],messageKey:"storyLocations.yaniv.scenes.electricalOutside.toolboxMessage"}
      ]
    },
    electrical_inside:{
      image:"yaniv_electrical_room_inside.webp",
      titleKey:"storyLocations.yaniv.scenes.electricalInside.title",
      hintKey:"storyLocations.yaniv.scenes.electricalInside.hint",
      parent:"electrical_outside",
      areas:[
        {id:"yaniv_spare_fuse",box:[4,78,28,14],checkAt:[18,84],loot:[{id:"yaniv_spare_fuse",qty:1}],titleKey:"storyLocations.yaniv.scenes.electricalInside.fuseTitle",icon:"⚡",descriptionKey:"storyLocations.yaniv.scenes.electricalInside.fuseDescription",messageKey:"storyLocations.yaniv.scenes.electricalInside.fuseMessage"},
        {id:"yaniv_power_restored",box:[33,54,39,22],checkAt:[53,64],requires:["yaniv_spare_fuse"],failKey:"storyLocations.yaniv.scenes.electricalInside.powerLocked",titleKey:"storyLocations.yaniv.scenes.electricalInside.powerTitle",icon:"⚡",descriptionKey:"storyLocations.yaniv.scenes.electricalInside.powerDescription",messageKey:"storyLocations.yaniv.scenes.electricalInside.powerMessage"}
      ]
    },
    service_post_outside:{
      image:"yaniv_service_post_outside.webp",
      introKey:"storyIntro.yaniv.servicePost",
      titleKey:"storyLocations.yaniv.scenes.servicePostOutside.title",
      hintKey:"storyLocations.yaniv.scenes.servicePostOutside.hint",
      parent:"main",
      areas:[
        {target:"service_post_inside",box:[42,28,26,35],marker:[55,45],labelKey:"storyLocations.yaniv.scenes.servicePostOutside.enter"},
        {id:"yaniv_service_post_order",box:[55,68,18,10],checkAt:[64,72],titleKey:"storyLocations.yaniv.scenes.servicePostOutside.orderTitle",icon:"📄",descriptionKey:"storyLocations.yaniv.scenes.servicePostOutside.orderDescription",messageKey:"storyLocations.yaniv.scenes.servicePostOutside.orderMessage"}
      ]
    },
    service_post_inside:{
      image:"yaniv_service_post_inside.webp",
      titleKey:"storyLocations.yaniv.scenes.servicePostInside.title",
      hintKey:"storyLocations.yaniv.scenes.servicePostInside.hint",
      parent:"service_post_outside",
      areas:[
        {id:"yaniv_military_pass",box:[30,61,26,16],checkAt:[43,68],loot:[{id:"yaniv_military_pass",qty:1}],titleKey:"storyLocations.yaniv.scenes.servicePostInside.passTitle",icon:"🪪",descriptionKey:"storyLocations.yaniv.scenes.servicePostInside.passDescription",messageKey:"storyLocations.yaniv.scenes.servicePostInside.passMessage"},
        {id:"yaniv_service_medkit",box:[76,70,19,13],checkAt:[85,76],loot:[{id:"medkit",qty:1}],messageKey:"storyLocations.yaniv.scenes.servicePostInside.medkitMessage"},
        {id:"yaniv_service_food",box:[49,83,14,11],checkAt:[56,88],loot:[{id:"food",qty:1}],messageKey:"storyLocations.yaniv.scenes.servicePostInside.foodMessage"}
      ]
    },
    service_route:{
      image:"yaniv_chnpp_service_route.webp",
      introKey:"storyIntro.yaniv.route",
      titleKey:"storyLocations.yaniv.scenes.serviceRoute.title",
      hintKey:"storyLocations.yaniv.scenes.serviceRoute.hint",
      parent:"main",
      areas:[
        {id:"yaniv_route_open",box:[17,50,12,18],checkAt:[22,59],requires:["yaniv_emergency_route_map","yaniv_power_restored","yaniv_military_pass"],failKey:"storyLocations.yaniv.scenes.serviceRoute.locked",titleKey:"storyLocations.yaniv.scenes.serviceRoute.openTitle",icon:"🚧",descriptionKey:"storyLocations.yaniv.scenes.serviceRoute.openDescription",messageKey:"storyLocations.yaniv.scenes.serviceRoute.openMessage"},
        {box:[52,28,33,35],labelKey:"storyLocations.yaniv.scenes.serviceRoute.exit",visibleAfter:["yaniv_route_open"],stageTarget:"chnpp",forwardArrow:true,messageKey:"storyLocations.yaniv.scenes.serviceRoute.exitMessage"}
      ]
    }
  }
};
